version: '3.8'
name: eduardosilvapereira
services:
  app:
    image: eduardosilvapereira.com
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
