# DEPLOY
name: Build Nextjs application and Deploy to Ubuntu Server on Digital Ocean

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ vars.DEPLOY_NODE_VERSION }} to build
        uses: actions/setup-node@v2
        with:
          node-version: ${{ vars.DEPLOY_NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: ssh deploy to Ubuntu Server on Digital Ocean
        uses: easingthemes/ssh-deploy@main
        env:
          ARGS: '-rlgoDzvc --delete'
          SOURCE: '/'
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ vars.DEPLOY_REMOTE_HOST }}
          REMOTE_USER: ${{ vars.DEPLOY_REMOTE_USER }}
          REMOTE_PORT: ${{ vars.DEPLOY_REMOTE_PORT }}
          TARGET: ${{ vars.DEPLOY_TARGET }}
